### PR TITLE
Redesigned website

### PR DESCRIPTION
**Pull request by JonahAragon**
**Major changes, so don't just merge this immediately** :stuck_out_tongue_closed_eyes:

I redesigned the entire website to make it look a bit more modern, and it's a one page design now. let me know what you think and if it's anything you'd consider :) 

Edit: It'll probably be easier to look at https://github.com/JonahAragon/butterproject.github.io rather than the commit changes, since it's all just full of deleting files.

I just copied content from your old webpage, so that's what all of it is pretty much.

Or... Way too many images! 

* https://gyazo.com/1472d768bc48bbb1f6ece3886d0d4ec0
* https://gyazo.com/361118a283d6c2fc383906076d8a4f64
* https://gyazo.com/70546f47fc4afc5b9318ef434b66e11a
* https://gyazo.com/cf824cd34739c965955c1a0f13c69b19
* https://gyazo.com/065065f0cc1fecfef37939d152d7234d
* https://gyazo.com/5b7786c9789daa74701c6c6a92215126
* https://gyazo.com/3a08bba7263eaeda67beebfa3bf40aed

### CODE REVIEW

**Comment by MrAdder** [comment]
I am going to say No to the Redesign at this time

**Comment by streger** [comment]
Too many dependencies that are not used, and that could be done more easily, but thanks for contributing. Try to clean it up.

**Comment by insertc0in** [comment]
I like the look, but... what they said ^

**Comment by xaiki** [comment]
hey I acually like it, we have another redesign idea pushed in new, and should look at wording and other things, can you please keep it around ?

**Comment by JonahAragon** [comment]
I'll clean it up and see what you think after :wink:

**Comment by MrAdder** [comment]
He is refering to the design

**Comment by xaiki** [comment]
also keep in mind that we need stuff to be translatable, that was done in the former website.

**Pull request closed without merging**
