### PR TITLE
Comment out dead link

### PR DESCRIPTION
**Pull request by samtarling**
Having no link is better than having a dead link imho - could be worth pointing it to blog.html or something in the future

### CODE REVIEW

**Comment by xaiki** [comment]
it should redirect, fixing dns.

**Comment by xaiki** [comment]
ok, so the dns was 'right' but your patch still applies, can you change it to point to # please ?

**Comment by samtarling** [comment]
@xaiki Done

**Comment by xaiki** [comment]
thanks for your contribution !

**Pull request merged**
