### PR TITLE
Did some work on Site, made it much more mobile friendly :)

### PR DESCRIPTION
**Pull request by ZakariaRidouh**
Made the site much more mobile friendly. Also, can someone with Chrome Dev/Beta (updated) see if the colored title bar works? Thanks!

### CODE REVIEW

**Comment by TheMightyCraken** [comment]
Any update on this?

**Comment by MrAdder** [comment]
Compiling and Testing sorry I have been out of the office for way too long

**Comment by MrAdder** [comment]
Unfortuanetly this makes the site look like

**Comment by TheMightyCraken** [comment]
Ok, it should work now :)

**Comment by PinhaS** [comment]
@TheMightyCraken , do you want me to see if it works ?  
i have the chrome dev build installed, and i can also test it on opera, i'm on dev edition too.

**Comment by TheMightyCraken** [comment]
@PinhaS Yes Please! Thanks!

**Comment by xaiki** [comment]
this touches a lot of different things that have nothing to do with mobile,
we're moving to `feature/new` soon, we're not going to merge that now, sorry for the delay.

**Pull request closed without merging**
