### PR TITLE
Use GitHub icon in social icons

### PR DESCRIPTION
**Pull request by malonehedges**

### CODE REVIEW

**Comment by mgarciaisaia** [comment]
@malonehedges I think you should change this on the `source` branch instead of `master`.

**Comment by MrAdder** [comment]
Please Change this on Source and Resubmit the PR

**Comment by xaiki** [comment]
merged by @MrAdder

**Comment by malonehedges** [comment]
@MrAdder Thanks, didn't see the source branch.

**Comment by MrAdder** [comment]
No problem the source branch is now default and all changes should be made there

**Pull request closed without merging**
